services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_container_inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
